---

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items:
    - "{{ cask_manifest }}"

# Link to Alfred, not using Alfred ATM
#- name: Link cask apps to Alfred
#  command: brew cask alfred

- name: Cleanup casks
  command: brew cask cleanup
