---
homebrew_installed_packages:
  - dockutil

homebrew_cask_apps:
  - hyperdock
  # - hyperswitch
  - bartender
  - caffeine
  - adobe-acrobat-reader
  - calibre
  - daisydisk
  - skype
  - slack
  - google-chrome
  - firefox
  - opera
  - google-backup-and-sync
  - dropbox
  - lastfm

mas_installed_apps:
  - name: Amphetamine
    id: 937984704
  - name: Magnet
    id: 441258766
  - name: Monit
    id: 1014850245
  - name: Reeder 3
    id: 880001334
  - name: Wunderlist
    id: 410628904

dockitems_to_remove:
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Pages
  - Photos
  - FaceTime
  - iBooks
  - App Store
  - System Preferences

dockitems_to_persist:
  - name: VirtualBox
    path: /Applications/VirtualBox.app
    position: 2
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    position: 5
