---
- hosts: all
  vars:
  # vars_prompt:
  #   - name: app_store_email
  #     prompt: Mac Apple Store ID
  #     private: no
  #     default: dieterblomme@gmail.com
  #     when: app_store_email is undefined
  #   - name: app_store_password
  #     prompt: Mac Apple Store Password
  #     private: yes
  #     default: 'Hb#Ym618nN'
  #     when: app_store_password is undefined
  tasks:
    - import_role:
        name: helpers
        tasks_from: sudo
    - import_role:
        name: general
    - import_role:
        name: shells
    - import_role:
        name: development
    - import_role:
        name: development-web
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
