---
- hosts: all
  vars:
    dockitems_enabled:
      - name: Google Chrome
        path: /Applications/Google Chrome.app
        pos: 2
      - name: Mail
        path: /Applications/Mail.app
        pos: 3
      - name: Calendar
        path: /Applications/Calendar.app
        pos: 4
      - name: Slack
        path: /Applications/Slack.app
        pos: 5
      - name: Reeder
        path: /Applications/Reeder.app
        pos: 6
      - name: MAMP PRO
        path: /Applications/MAMP PRO/MAMP PRO.app
        pos: 7
      - name: PhpStorm
        path: /Applications/PhpStorm.app
        pos: 8
      - name: Sublime Text
        path: /Applications/Sublime Text.app
        pos: 9
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 10
      - name: Tower
        path: /Applications/Tower.app
        pos: 11
      - name: Sequel Pro
        path: /Applications/Sequel Pro.app
        pos: 12
  vars_prompt:
    - name: app_store_email
      prompt: Mac Apple Store ID
      private: no
      when: app_store_email is undefined
    - name: app_store_password
      prompt: Mac Apple Store Password
      private: yes
      when: app_store_password is undefined
  tasks:
    - import_role:
        name: general
    - import_role:
        name: shells
    - import_role:
        name: development
    - import_role:
        name: development-web
    - import_role:
        name: development-chef
    - import_role:
        name: fubarhouse.macdock
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
