---
- hosts: all
  gather_facts: false
  tasks:
    - setup:
        gather_subset: "!ohai"
      tags:
      - always
    - import_role:
        name: general
    - import_role:
        name: shells
      tags:
      - shells
    - import_role:
        name: development
      tags:
      - development
    - import_role:
        name: development-web
    - import_role:
        name: development-chef
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
