---
- hosts: all
  vars:
    dockitems_remove_all: true
    dockitems_enabled:
      - name: Firefox
        path: /Applications/Firefox.app
        pos: 2
      - name: Google Chrome
        path: /Applications/Google Chrome.app
        pos: 3
      - name: Calendar
        path: /Applications/Calendar.app
        pos: 4
      - name: Slack
        path: /Applications/Slack.app
        pos: 5
      - name: Reeder
        path: /Applications/Reeder.app
        pos: 6
      - name: PhpStorm
        path: /Applications/PhpStorm.app
        pos: 7
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app
        pos: 8
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 9
      - name: Sublime Merge
        path: /Applications/Sublime Merge.app
        pos: 10
      - name: Sequel Pro
        path: /Applications/Sequel Pro.app
        pos: 11
    ssl_organization: "Picabit"
  gather_facts: false
  tasks:
    - setup:
        gather_subset: "!ohai"
      tags:
      - always
    - import_role:
        name: general
    - import_role:
        name: shells
      tags:
      - shells
    - import_role:
        name: development
      tags:
      - development
    - import_role:
        name: development-web
    - import_role:
        name: development-chef
    - import_role:
        name: picabit
    - import_role:
        name: fubarhouse.macdock
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
