---
- hosts: all
  tasks:
    - import_role:
        name: general
    - import_role:
        name: shells
    - import_role:
        name: development
    - import_role:
        name: development-web
    - import_role:
        name: development-chef
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
