---
- name: restart cfprefsd
  command: killall cfprefsd
  ignore_errors: yes

- name: restart MenuBar
  command: killall SystemUIServer
  ignore_errors: yes

- name: restart Dock
  command: killall Dock
  ignore_errors: yes

- name: restart Finder
  command: killall Finder
  ignore_errors: yes
