---
###############################################################################
# Activity Monitor                                                            #
###############################################################################

- name: Show the main window when launching Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
    state: present
  notify: restart Activity Monitor

- name: Visualize CPU usage in the Activity Monitor Dock icon
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: IconType
    type: integer
    value: 5
    state: present
  notify: restart Activity Monitor

- name: Show all processes in Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: integer
    value: 0
    state: present
  notify: restart Activity Monitor

- name: Sort Activity Monitor results by CPU usage
  block:
    - osx_defaults:
        domain: com.apple.ActivityMonitor
        key: SortColumn
        type: string
        value: CPUUsage
        state: present
      notify: restart Activity Monitor
    - osx_defaults:
        domain: com.apple.ActivityMonitor
        key: SortDirection
        type: integer
        value: 0
        state: present
      notify: restart Activity Monitor
