---
###############################################################################
# Mac App Store                                                               #
###############################################################################

# - name: Enable the WebKit Developer Tools in the Mac App Store
#   osx_defaults:
#     domain: com.apple.SoftwareUpdate
#     key: WebKitDeveloperExtras
#     type: bool
#     value: true
#     state: present

# - name: Enable Debug Menu in the Mac App Store
#   osx_defaults:
#     domain: com.apple.SoftwareUpdate
#     key: ShowDebugMenu
#     type: bool
#     value: true
#     state: present

- name: Enable the automatic update check
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    type: bool
    value: true
    state: present

- name: Check for software updates daily, not just once per week
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: integer
    value: 1
    state: present

- name: Download newly available updates in background
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    type: integer
    value: 1
    state: present

- name: Install System data files & security updates
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    type: integer
    value: 1
    state: present

# - name: Automatically download apps purchased on other Macs
#   osx_defaults:
#     domain: com.apple.SoftwareUpdate
#     key: ConfigDataInstall
#     type: integer
#     value: 1
#     state: present

- name: Turn on app auto-update
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutoUpdate
    type: bool
    value: true
    state: present

- name: Allow the App Store to reboot machine on macOS updates
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: AutoUpdateRestartRequired
    type: bool
    value: true
    state: present
