---
###############################################################################
# Dock, Dashboard, and hot corners                                            #
###############################################################################

# Add applications to the Dock
# First item needs -array; other items -array-add
# defaults write com.apple.dock persistent-apps -array '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Google Chrome.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Microsoft Outlook.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Calendar.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Slack.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Reeder.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Evernote.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/MAMP PRO.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/PhpStorm.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Sublime Text.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/iTerm.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Tower.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Transmit.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Sequel Pro.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
# defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/System Preferences.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'

# Add folders to the Dock extra items
# First item needs -array; other items -array-add
# defaults write com.apple.dock persistent-others -array '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications</string><key>_CFURLStringType</key><integer>0</integer></dict><key>displayas</key><integer>1</integer></dict><key>tile-type</key><string>directory-tile</string></dict>'
# defaults write com.apple.dock persistent-others -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>${HOME}/Downloads</string><key>_CFURLStringType</key><integer>0</integer></dict><key>displayas</key><integer>1</integer></dict><key>tile-type</key><string>directory-tile</string></dict>"

# Add a spacer to the left side of the Dock (where the applications are)
#defaults write com.apple.dock persistent-apps -array-add '{tile-data={}; tile-type="spacer-tile";}'
# Add a spacer to the right side of the Dock (where the Trash is)
#defaults write com.apple.dock persistent-others -array-add '{tile-data={}; tile-type="spacer-tile";}'

- name: Set the Dock to the right of the screen
  osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: right
    state: present

- name: Enable highlight hover effect for the grid view of a stack (Dock)
  osx_defaults:
    domain: com.apple.dock
    key: mouse-over-hilite-stack
    type: bool
    value: true
    state: present

- name: Set the icon size of Dock items to 41 pixels
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 41
    state: present

- name: Change minimize/maximize window effect
  osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: scale
    state: present

- name: Minimize windows into their application’s icon
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
    state: present

- name: Enable spring loading for all Dock items
  osx_defaults:
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: true
    state: present

- name: Show indicator lights for open applications in the Dock
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: true
    state: present

- name: Magnify the dock
  block:
    - osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: true
        state: present
    - osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: float
        value: 77.2013854980469
        state: present

# - name: Show only open applications in the Dock
#   osx_defaults:
#     domain: com.apple.dock
#     key: static-only
#     type: bool
#     value: true
#     state: present

- name: Don’t animate opening applications from the Dock
  osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: true
    state: present

- name: Speed up Mission Control animations
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.1
    state: present

- name: Don’t group windows by application in Mission Control (i.e. use the old Exposé behavior instead)
  osx_defaults:
    domain: com.apple.dock
    key: expose-group-by-app
    type: bool
    value: false
    state: present

- name: Disable Dashboard
  osx_defaults:
    domain: com.apple.dashboard
    key: mcx-disabled
    type: bool
    value: true
    state: present

- name: Don’t show Dashboard as a Space
  osx_defaults:
    domain: com.apple.dock
    key: dashboard-in-overlay
    type: bool
    value: true
    state: present

# - name: Displays have separate Spaces
#   osx_defaults:
#     domain: com.apple.spaces
#     key: spans-displays
#     type: bool
#     value: false
#     state: present

- name: Don’t automatically rearrange Spaces based on most recent use
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
    state: present

- name: Remove the auto-hiding Dock delay
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    state: present

- name: Remove the animation when hiding/showing the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: 0
    state: present

- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

- name: Make Dock icons of hidden applications translucent
  osx_defaults:
    domain: com.apple.dock
    key: showhidden
    type: bool
    value: true
    state: present

- name: Disable the Launchpad gesture (pinch with thumb and three fingers)
  osx_defaults:
    domain: com.apple.dock
    key: showLaunchpadGestureEnabled
    type: int
    value: 0
    state: present

- name: Reset Launchpad, but keep the desktop wallpaper intact
  block:
    - find:
        paths: "~/Library/Application Support/Dock"
        patterns: "*-*.db"
      register: dock_db_files
    - file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ dock_db_files.files }}"

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center

- name: Top left screen corner → Mission Control
  block:
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-corner
        type: int
        value: 2
        state: present
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-modifier
        type: int
        value: 524288
        state: present
- name: Top right screen corner → Desktop
  block:
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-corner
        type: int
        value: 4
        state: present
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-modifier
        type: int
        value: 524288
        state: present
- name: Bottom left screen corner → Start screen saver
  block:
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-corner
        type: int
        value: 5
        state: present
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-modifier
        type: int
        value: 524288
        state: present
- name: Bottom right screen corner → Put display to sleep
  block:
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-corner
        type: int
        value: 10
        state: present
    - osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-modifier
        type: int
        value: 524288
        state: present
