---
###############################################################################
# Finder                                                                      #
###############################################################################

- set_fact: 'plistbuddy=/usr/libexec/PlistBuddy'
- set_fact: 'finder_plist=~/Library/Preferences/com.apple.finder.plist'
- set_fact: 'dropbox_icon=/Applications/Dropbox.app/Contents/Resources/emblem-dropbox-uptodate.icns'

# Check if FK_StandardViewSettings exists in finder_plist
- command: '{{ plistbuddy }} -c "print FK_StandardViewSettings" {{ finder_plist }} 2>/dev/null'
  register: FK_StandardViewSettings
  ignore_errors: true
  changed_when: false

- name: "Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons"
  osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: "Finder: disable window animations and Get Info animations"
  osx_defaults:
    domain: com.apple.finder
    key: DisableAllAnimations
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: "Set Workspaces as the default location for new Finder windows"
# For Desktop, use `PfDe` and `file://${HOME}/Desktop/`
  block:
    - osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: PfLo
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: file://${HOME}/Desktop/
        state: present
      notify: restart Finder
- name: "Show icons for hard drives, servers, and removable media on the desktop"
  block:
    - osx_defaults:
        domain: com.apple.finder
        key: ShowExternalHardDrivesOnDesktop
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.finder
        key: ShowHardDrivesOnDesktop
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.finder
        key: ShowMountedServersOnDesktop
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.finder
        key: ShowRemovableMediaOnDesktop
        type: bool
        value: true
        state: present
      notify: restart Finder
# - name: "Finder: show hidden files by default"
#   osx_defaults:
#     domain: com.apple.finder
#     key: AppleShowAllFiles
#     type: bool
#     value: true
#     state: present
- name: "Finder: show all filename extensions"
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllExtensions
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: "Finder: show status bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: "Finder: show path bar"
  osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: Display full POSIX path as Finder window title
  osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: Keep folders on top when sorting by name
  osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: When performing a search, search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: SCcf
    state: present
  notify: restart Finder
- name: Disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: false
    state: present
  notify: restart Finder
- name: Enable spring loading for directories
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.enabled
    type: bool
    value: true
    state: present
  notify: restart Finder
- name: Remove the spring loading delay for directories
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.springing.delay
    type: float
    value: 0
    state: present
  notify: restart Finder
- name: Avoid creating .DS_Store files on network or USB volumes
  block:
    - osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteNetworkStores
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.desktopservices
        key: DSDontWriteUSBStores
        type: bool
        value: true
        state: present
      notify: restart Finder
- name: Disable disk image verification
  block:
    - osx_defaults:
        domain: com.apple.frameworks.diskimages
        key: skip-verify
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.frameworks.diskimages
        key: skip-verify-locked
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.frameworks.diskimages
        key: skip-verify-remote
        type: bool
        value: true
        state: present
      notify: restart Finder
- name: Automatically open a new Finder window when a volume is mounted
  block:
    - osx_defaults:
        domain: com.apple.frameworks.diskimages
        key: auto-open-ro-root
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.frameworks.diskimages
        key: auto-open-rw-root
        type: bool
        value: true
        state: present
      notify: restart Finder
    - osx_defaults:
        domain: com.apple.finder
        key: OpenWindowForNewRemovableDisk
        type: bool
        value: true
        state: present
      notify: restart Finder

- name: Show item info near icons on the desktop and in other icon views
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":DesktopViewSettings:IconViewSettings:showItemInfo"
      type: bool
      value: true
      plist: "{{ finder_plist }}"
    - name: ":FK_StandardViewSettings:IconViewSettings:showItemInfo"
      type: bool
      value: true
      plist: "{{ finder_plist }}"
    - name: ":StandardViewSettings:IconViewSettings:showItemInfo"
      type: bool
      value: true
      plist: "{{ finder_plist }}"
  notify: restart Finder

- name: Show item info near icons on the desktop and in other icon views
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":DesktopViewSettings:IconViewSettings:labelOnBottom"
      type: bool
      value: false
      plist: "{{ finder_plist }}"
  notify: restart Finder

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":DesktopViewSettings:IconViewSettings:arrangeBy"
      type: string
      value: grid
      plist: "{{ finder_plist }}"
    - name: ":FK_StandardViewSettings:IconViewSettings:arrangeBy"
      type: string
      value: grid
      plist: "{{ finder_plist }}"
    - name: ":StandardViewSettings:IconViewSettings:arrangeBy"
      type: string
      value: grid
      plist: "{{ finder_plist }}"
  notify: restart Finder

- name: Increase grid spacing for icons on the desktop and in other icon views
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":DesktopViewSettings:IconViewSettings:gridSpacing"
      type: integer
      value: 100
      plist: "{{ finder_plist }}"
    - name: ":FK_StandardViewSettings:IconViewSettings:gridSpacing"
      type: integer
      value: 100
      plist: "{{ finder_plist }}"
    - name: ":StandardViewSettings:IconViewSettings:gridSpacing"
      type: integer
      value: 100
      plist: "{{ finder_plist }}"
  notify: restart Finder

- name: Increase the size of icons on the desktop and in other icon views
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":DesktopViewSettings:IconViewSettings:iconSize"
      type: integer
      value: 80
      plist: "{{ finder_plist }}"
    - name: ":FK_StandardViewSettings:IconViewSettings:iconSize"
      type: integer
      value: 80
      plist: "{{ finder_plist }}"
    - name: ":StandardViewSettings:IconViewSettings:iconSize"
      type: integer
      value: 80
      plist: "{{ finder_plist }}"
  notify: restart Finder

- name: Use list view in all Finder windows by default
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
  osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: Nlsv
    state: present
  notify: restart Finder
- name: Disable the warning before emptying the Trash
  osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: false
    state: present
  notify: restart Finder
- name: Enable AirDrop over Ethernet and on unsupported Macs running Lion
  osx_defaults:
    domain: com.apple.NetworkBrowser
    key: BrowseAllInterfaces
    type: bool
    value: false
    state: present
  notify: restart Finder

- name: Check if ~/Library is hidden
  shell: ls -aOl ~/Library | sed -n 2p
  ignore_errors: true
  changed_when: false
  register: library_hidden
- name: Show the ~/Library folder
  command: chflags nohidden ~/Library
  when: library_hidden.stdout | search("hidden")
  notify: restart Finder

- name: Check if /Volumes is hidden
  shell: ls -aOl /Volumes | sed -n 2p
  become: yes
  ignore_errors: true
  changed_when: false
  register: volumes_hidden
- name: Show the /Volumes folder
  command: chflags nohidden /Volumes
  become: yes
  when: volumes_hidden.stdout | search("hidden")
  notify: restart Finder

- stat:
    path: "{{ dropbox_icon }}"
  register: dropbox_icon_exists
- name: Remove Dropbox’s green checkmark icons in Finder
  copy:
    remote_src: yes
    src: "{{ dropbox_icon }}"
    dest: "{{ dropbox_icon }}.bak"
  when: dropbox_icon_exists.stat.exists
  notify: restart Finder

- name: 'Expand the following File Info panes: “General”, “Open with”, and “Sharing & Permissions”'
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: :FXInfoPanesExpanded
      type: ''
      value: dict
      plist: "{{ finder_plist }}"
    - name: :FXInfoPanesExpanded:General
      type: bool
      value: true
      plist: "{{ finder_plist }}"
    - name: :FXInfoPanesExpanded:OpenWith
      type: bool
      value: true
      plist: "{{ finder_plist }}"
    - name: :FXInfoPanesExpanded:Privileges
      type: bool
      value: true
      plist: "{{ finder_plist }}"
  notify: restart Finder
