---
###############################################################################
# Google Chrome & Google Chrome Canary                                        #
###############################################################################

- name: Disable the all too sensitive backswipe on trackpads
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: false
    state: present
  notify: restart Google Chrome

- name: Disable the all too sensitive backswipe on Magic Mouse
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableMouseSwipeNavigateWithScrolls
    type: bool
    value: false
    state: present
  notify: restart Google Chrome

- name: Use the system-native print preview dialog
  osx_defaults:
    domain: com.google.Chrome
    key: DisablePrintPreview
    type: bool
    value: true
    state: present
  notify: restart Google Chrome

- name: Expand the print dialog by default
  osx_defaults:
    domain: com.google.Chrome
    key: PMPrintingExpandedStateForPrint2
    type: bool
    value: true
    state: present
  notify: restart Google Chrome
