---
- name: Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
  command: osascript -e 'tell application "System Preferences" to quit'
  changed_when: false

# General OS settings
- import_tasks: ui_ux.yml
- import_tasks: ssd_tweaks.yml
- import_tasks: trackpad_mouse_btaccessories.yml
- import_tasks: input.yml
- import_tasks: soundoutput.yml
- import_tasks: screen.yml
- import_tasks: finder.yml
- import_tasks: dock.yml
- import_tasks: touchbar.yml
- import_tasks: spotlight.yml
- import_tasks: time_machine.yml
- import_tasks: activity_monitor.yml
- import_tasks: app_store.yml
- import_tasks: mail.yml
- import_tasks: messages.yml
- import_tasks: photos.yml

# Application settings
- import_tasks: google_chrome.yml
- import_tasks: transmission.yml
- import_tasks: amphetamine.yml
- import_tasks: magnet.yml
- import_tasks: hyperdock.yml
- import_tasks: reeder.yml
