---
- name: Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
  command: osascript -e 'tell application "System Preferences" to quit'
  changed_when: false

- import_tasks: ui_ux.yml
- import_tasks: ssd_tweaks.yml
- import_tasks: trackpad_mouse_btaccessories.yml
- import_tasks: input.yml
- import_tasks: screen.yml
- import_tasks: finder.yml
- import_tasks: dock.yml
- import_tasks: spotlight.yml
- import_tasks: time_machine.yml
- import_tasks: activity_monitor.yml
- import_tasks: app_store.yml
- import_tasks: photos.yml
- import_tasks: google_chrome.yml
