---
- name: Install general casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - "{{ casks_general }}"

- name: Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
  command: osascript -e 'tell application "System Preferences" to quit'

- include: system.yml
- include: ssd_tweaks.yml
- include: trackpad_mouse_btaccessories.yml
- include: input.yml
- include: screen.yml
- include: finder.yml
- include: dock.yml
