---

- name: Open browser links in background
  osx_defaults:
    domain: com.reederapp.rkit2.mac
    key: OpenLinksInBackground
    type: int
    value: 1
    state: present

- name: Don't ask before marking all as read
  osx_defaults:
    domain: com.reederapp.rkit2.mac
    key: ConfirmMarkAllAsRead
    type: int
    value: 0
    state: present
