---

- name: Open browser links in background
  osx_defaults:
    domain: com.reederapp.rkit2.mac
    key: OpenLinksInBackground
    type: bool
    value: true
    state: present

- name: Don't ask before marking all as read
  osx_defaults:
    domain: com.reederapp.rkit2.mac
    key: ConfirmMarkAllAsRead
    type: bool
    value: false
    state: present
