---
###############################################################################
# SSD-specific tweaks                                                         #
###############################################################################

- name: Check disable hibernation
  command: pmset -g
  become: yes
  ignore_errors: true
  changed_when: false
  register: pmset
- name: Disable hibernation (speeds up entering sleep mode)
  command: pmset -a hibernatemode 0
  become: yes
  when: not pmset.stdout | search("hibernatemode\s*0")

# Disabled for now since SIP prevents this manipulation
# - name: "Remove the sleep image file to save disk space"
#   file:
#     path: /private/var/vm/sleepimage
#     state: absent
#   become: yes
# - name: "Create a zero-byte file instead…"
#   command: "touch /private/var/vm/sleepimage"
#   become: yes
# - name: "…and make sure it can’t be rewritten"
#   command: "chflags uchg /private/var/vm/sleepimage"
#   become: yes
