---
###############################################################################
# Time Machine                                                                #
###############################################################################

- name: Prevent Time Machine from prompting to use new hard drives as backup volume
  osx_defaults:
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    type: bool
    value: true
    state: present
  notify: restart Dock

- name: Disable local Time Machine backups
  shell: hash tmutil &> /dev/null && sudo tmutil disablelocal
