---
###############################################################################
# Transmission.app                                                            #
###############################################################################

- name: Use `~/Documents/Torrents` to store incomplete downloads
  block:
    - osx_defaults:
        domain: org.m0k.transmission
        key: UseIncompleteDownloadFolder
        type: bool
        value: true
        state: present
      notify: restart Transmission
    - osx_defaults:
        domain: org.m0k.transmission
        key: IncompleteDownloadFolder
        type: string
        value: "${HOME}/Documents/Torrents"
        state: present
      notify: restart Transmission

- name: Use `~/Downloads` to store completed downloads
  osx_defaults:
    domain: org.m0k.transmission
    key: DownloadLocationConstant
    type: bool
    value: true
    state: present
  notify: restart Transmission

- name: Don’t prompt for confirmation before downloading
  block:
    - osx_defaults:
        domain: org.m0k.transmission
        key: DownloadAsk
        type: bool
        value: false
        state: present
      notify: restart Transmission
    - osx_defaults:
        domain: org.m0k.transmission
        key: MagnetOpenAsk
        type: bool
        value: false
        state: present
      notify: restart Transmission

- name: Don’t prompt for confirmation before removing non-downloading active transfers
  osx_defaults:
    domain: org.m0k.transmission
    key: CheckRemoveDownloading
    type: bool
    value: true
    state: present
  notify: restart Transmission

- name: Trash original torrent files
  osx_defaults:
    domain: org.m0k.transmission
    key: DeleteOriginalTorrent
    type: bool
    value: true
    state: present
  notify: restart Transmission

- name: Hide the donate message
  osx_defaults:
    domain: org.m0k.transmission
    key: WarningDonate
    type: bool
    value: false
    state: present
  notify: restart Transmission

- name: Hide the legal disclaimer
  osx_defaults:
    domain: org.m0k.transmission
    key: WarningLegal
    type: bool
    value: false
    state: present
  notify: restart Transmission

- name: IP block list.
# Source: https://giuliomac.wordpress.com/2014/02/19/best-blocklist-for-transmission/
  block:
    - osx_defaults:
        domain: org.m0k.transmission
        key: BlocklistNew
        type: bool
        value: true
        state: present
      notify: restart Transmission
    - osx_defaults:
        domain: org.m0k.transmission
        key: BlocklistURL
        type: string
        value: http://john.bitsurge.net/public/biglist.p2p.gz
        state: present
      notify: restart Transmission
    - osx_defaults:
        domain: org.m0k.transmission
        key: BlocklistAutoUpdate
        type: bool
        value: true
        state: present
      notify: restart Transmission

- name: Randomize port on launch
  osx_defaults:
    domain: org.m0k.transmission
    key: RandomPort
    type: bool
    value: false
    state: present
  notify: restart Transmission
