---

- name: Check if there is a loginitem with name {{ item.name }}
  command: "osascript -e 'tell application \"System Events\" to get the name of every login item'"
  register: login_items
  changed_when: false

- name: Add login item {{ item.name }}
  command: "osascript -e 'tell application \"System Events\" to make login item at end with properties {name: \"{{ item.name }}\", path: \"{{ item.path }}\", hidden:false}'"
  when:
    - login_items is succeeded
    - not login_items.stdout is search(item.name) 
