---

- name: Make sure we have a '{{ sudo_group }}' group
  group:
    name: "{{ sudo_group }}"
    state: present
- name: Allow '{{ sudo_group }}' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
  become: yes
- name: Add {{ sudo_user }} users to {{ sudo_group }} group
  user:
    name: "{{ sudo_user }}"
    groups: "{{ sudo_group }}"
    append: yes
    state: present
  become: yes
