---
- name: Install brew and prerequisites
  include: brew.yml

- name: Tap the main taps we need
  include: taps.yml

- name: Install prerequisites
  homebrew: name={{ item }} state=present
  run_once: true
  with_items:
    - "{{ brew_utils }}"

- name: Update OpenSSH
  homebrew: name=openssh state=present install_options=with-brewed-openssl,with-keychain-support

- name: Link all apps
  command: brew linkapps

- name: Clean up
  command: brew cleanup
