---

# Config files for tools

- name: Install .editorconfig
  copy:
    src: files/.editorconfig
    dest: ~/.editorconfig

- name: Install .gitconfig
  copy:
    src: files/.gitconfig
    dest: ~/.gitconfig

- name: Install .gitignore
  copy:
    src: files/.gitignore
    dest: ~/.gitignore

- name: Install .gvimrc
  copy:
    src: files/.gvimrc
    dest: ~/.gvimrc

- name: Install .vimrc
  copy:
    src: files/.vimrc
    dest: ~/.vimrc

- copy:
    src: files/.vim
    dest: ~/

# Application config

- import_tasks: tower.yml
