---

- import_tasks: vim.yml

# Install git-lfs and install it
- name: Install git-lfs
  homebrew:
    name: git-lfs
    state: present
  notify: install git-lfs

# Config files for tools

- name: Install .editorconfig
  copy:
    src: files/.editorconfig
    dest: ~/.editorconfig

- name: Install .gitattributes
  copy:
    src: files/.gitattributes
    dest: ~/.gitattributes

- name: Install .gitconfig
  copy:
    src: files/.gitconfig
    dest: ~/.gitconfig

- name: Install .gitignore
  copy:
    src: files/.gitignore
    dest: ~/.gitignore

# Application config

- import_tasks: tower.yml

- name: "Finder: show hidden files by default"
  osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: string
    value: 'YES'
    state: present
