---

# Install pathogen.vim (https://github.com/tpope/vim-pathogen)
- name: Create ~/.vim/autoload folder
  file:
    path: ~/.vim/autoload
    state: directory
    mode: 0755

- name: Download pathogen.vim
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: ~/.vim/autoload/pathogen.vim

# Install sensible vim
- name: Create ~/.vim/bundle folder
  file:
    path: ~/.vim/bundle
    state: directory
    mode: 0755

- name: Install .vimrc
  copy:
    src: files/.vimrc
    dest: ~/.vimrc

# Use .gvimrc for macvim
- name: Install .gvimrc
  copy:
    src: files/.gvimrc
    dest: ~/.gvimrc

- name: Install sensible-vim
  git:
    repo: "https://github.com/tpope/vim-sensible.git"
    dest: ~/.vim/bundle/vim-sensible

- name: Install fzf.vim
  git:
    repo: "https://github.com/junegunn/fzf.vim.git"
    dest: ~/.vim/bundle/fzf.vim
- name: Install fzf
  git:
    repo: "https://github.com/junegunn/fzf.git"
    dest: ~/.vim/bundle/fzf
