---

- name: Install .vimrc
  copy:
    src: files/.vimrc
    dest: ~/.vimrc

- copy:
    src: files/.vim
    dest: ~/

# Use .gvimrc for macvim
- name: Install .gvimrc
  copy:
    src: files/.gvimrc
    dest: ~/.gvimrc
