---
###############################################################################
# iTerm 2                                                                     #
###############################################################################

- set_fact: 'iterm2_plist=~/Library/Preferences/com.googlecode.iterm2.plist'

# - name: Install the Solarized Dark theme for iTerm
#   block:
#     - file:
#         path: ~/init
#         state: directory
#         mode: 0755
#     - get_url:
#         url: https://raw.githubusercontent.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors
#         dest: ~/init/Solarized Dark.itermcolors
#     - command: 'open "~/init/Solarized Dark.itermcolors"'

- name: Don’t display the annoying prompt when quitting iTerm
  osx_defaults:
    domain: com.googlecode.iterm2
    key: PromptOnQuit
    type: bool
    value: false
    state: present

- name: Also not when closing multiple sessions
  osx_defaults:
    domain: com.googlecode.iterm2
    key: OnlyWhenMoreTabs
    type: bool
    value: false
    state: present

- include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: :GlobalKeyMap
      type: ''
      value: dict
      plist: "{{ iterm2_plist }}"
    - name: :GlobalKeyMap:0xf702-0x380000
      type: ''
      value: dict
      plist: "{{ iterm2_plist }}"
    - name: :GlobalKeyMap:0xf702-0x380000:Text
      type: ''
      value: string
      plist: "{{ iterm2_plist }}"
    - name: :GlobalKeyMap:0xf702-0x380000:Action
      type: integer
      value: 2
      plist: "{{ iterm2_plist }}"
    - name: :GlobalKeyMap:0xf703-0x380000
      type: ''
      value: dict
      plist: "{{ iterm2_plist }}"
    - name: :GlobalKeyMap:0xf703-0x380000:Text
      type: ''
      value: string
      plist: "{{ iterm2_plist }}"
    - name: :GlobalKeyMap:0xf703-0x380000:Action
      type: integer
      value: 0
      plist: "{{ iterm2_plist }}"

# This section doesn't work yet:
- name: "Profile 1: Unlimited scrollback"
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: :'New Bookmarks':0:'Scrollback Lines'
      type: integer
      value: 0
      plist: "{{ iterm2_plist }}"
    - name: :'New Bookmarks':0:'Unlimited Scrollback'
      type: bool
      value: true
      plist: "{{ iterm2_plist }}"
- name: "Profile 1: Save lines to scrollback when an app status bar is present"
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":'New Bookmarks':0:'Scrollback With Status Bar'"
      type: bool
      value: true
      plist: "{{ iterm2_plist }}"
- name: "Profile 1: Make sure alt left/right work properly"
  include_role:
    name: helpers
    tasks_from: plistbuddy
  with_items:
    - name: ":'New Bookmarks':0:'Keyboard Map':0xf702-0x280000:Action"
      type: integer
      value: 10
      plist: "{{ iterm2_plist }}"
    - name: ":'New Bookmarks':0:'Keyboard Map':0xf702-0x280000:Text"
      type: string
      value: b
      plist: "{{ iterm2_plist }}"
    - name: ":'New Bookmarks':0:'Keyboard Map':0xf703-0x280000:Action"
      type: integer
      value: 10
      plist: "{{ iterm2_plist }}"
    - name: ":'New Bookmarks':0:'Keyboard Map':0xf703-0x280000:Text"
      type: string
      value: f
      plist: "{{ iterm2_plist }}"
