---
- set_fact: 'plistbuddy=/usr/libexec/PlistBuddy'
- set_fact: 'iterm2_plist=~/Library/Preferences/com.googlecode.iterm2.plist'

# Check if a key exists
- command: '{{ plistbuddy }} -c "Print {{ item.name }}" {{ iterm2_plist }}'
  register: check
  ignore_errors: true
- name: Set value with PlistBuddy
  command: '{{ plistbuddy }} -c "Set {{ item.name }} {{ item.value }}" {{ iterm2_plist }}'
  when:
    - check | succeeded
    - not item.value | search("dict")
    - not item.value == check.stdout
- name: Add value with PlistBuddy
  command: '{{ plistbuddy }} -c "Add {{ item.name }} {{ item.type }} {{ item.value }}" {{ iterm2_plist }}'
  when: check|failed
