---

# Temporary until MAMP hash is OK
# https://github.com/caskroom/homebrew-cask/pull/39485#issuecomment-336266363
- name: Fix sha for MAMP
  lineinfile:
    dest: "{{ homebrew_install_path }}/Library/Taps/caskroom/homebrew-cask/Casks/mamp.rb"
    state: present
    regexp: "^    sha256 '808e9685153c12a50d582e5eb27badbbc0cdc0df3fd3e0bf4bcaa74c4dc6a058'$"
    line: "    sha256 '9428a3cf494d02d94ecaec302042822f54273ba9d412ecde25d1155ab07db56e'"
  become: yes
- name: Install MAMP.
  homebrew_cask:
    name: mamp
    state: present
    install_options: "appdir={{ homebrew_cask_appdir }}"

- name: Ensure NPM version 5.4.2.
  npm:
    name: npm
    version: '5.4.2'
    global: yes
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
