---

- name: Ensure node is linked
  command: 'brew link node@10 --overwrite --force'

- name: Ensure NPM version 5.6.0.
  npm:
    name: npm
    version: '5.6.0'
    global: yes
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

# Application settings
- import_tasks: hammp.yml
- import_tasks: php-cli-tools.yml
- import_tasks: transmit.yml
