---

- name: Ensure NPM version 5.4.2.
  npm:
    name: npm
    version: '5.6.0'
    global: yes
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

# Application settings
- import_tasks: mamp.yml
- import_tasks: amp.yml
- import_tasks: transmit.yml
