---
###############################################################################
# PHP CLI tools                                                               #
###############################################################################

- name: Install PHP CLI tools from homebrew
  homebrew:
    name: httpd
    state: present
    install_options: with-brewed-openssl,with-mpm-event
  with_items:
    - composer
    - drush
    - php-code-sniffer
    - drupal-code-sniffer
    - phpmd
  tags:
    - php

- name: Install composer path .bashrc.d files
  copy:
    src: "files/.bashrc.d/composer_path.bashrc"
    dest: "~/.bashrc.d/composer_path.bashrc"
  tags:
    - php
