---

homebrew_taps:
  - caskroom/cask
  - bramstein/webfonttools # https://github.com/bramstein/homebrew-webfonttools

homebrew_installed_packages:
  - homebrew/php/php71
  - homebrew/php/php71-mcrypt
  - composer
  - drush
  - php-code-sniffer
  - drupal-code-sniffer
  - phpmd
  - symfony-installer
  - node
  - name: imagemagick
    install_options: --with-gettext
  - lynx # Text based web browser
  # Web font tools:
  - sfnt2woff
  - sfnt2woff-zopfli
  - woff2

homebrew_cask_apps:
  - phpstorm
  - mamp
  - sequel-pro
  - transmit
  - poedit
