---

homebrew_taps:
  - caskroom/cask
  - bramstein/webfonttools # https://github.com/bramstein/homebrew-webfonttools

homebrew_installed_packages:
  - node
  - name: imagemagick
    install_options: --with-gettext
  - lynx # Text based web browser
  # Web font tools:
  - sfnt2woff
  - sfnt2woff-zopfli
  - woff2

homebrew_cask_apps:
  - phpstorm
  - mamp
  - sequel-pro
  - transmit
  - poedit

php_configs:
  - { regexp: '^;?(max_execution_time) *=.*$',            replace: '\1 = 0' }
  - { regexp: '^;?(max_input_time) *=.*$',                replace: '\1 = -1' }
  - { regexp: '^;?(memory_limit) *=.*$',                  replace: '\1 = 512M' }
  - { regexp: '^;?(date.timezone) *=.*$',                 replace: '\1 = Europe/Brussels' }
