---

- name: Capture the path to the gem executable
  shell:  >
    executable=/bin/bash source /usr/local/share/chruby/chruby.sh;
    chruby ruby-{{ ruby_version }};
    which gem > /tmp/gem_executable;
  register: gem_executable

- name: Get gem executable from file
  command: cat /tmp/gem_executable
  register: gem_executable

- name: Show the executable we are going to use
  debug: msg="{{ gem_executable }}"

- name: Update the user gems
  shell: "{{ gem_executable.stdout | quote }} update"
  sudo: yes

- name: Install gems
  gem: name={{ item }} state=present user_install=yes executable="{{ gem_executable.stdout }}"
  with_items: gems

- name: Print gems
  shell: "{{ gem_executable.stdout | quote }} list"
