---
- name:     Check if the correct version of Ruby is already installed
  command:  "chruby"
  register: chruby_versions

- name:     Debug info
  debug:    msg="{{ chruby_versions.stdout }}"

- name:     Install the versions of Ruby we need
  shell:    ruby-install ruby {{ item }}
  when:     not rbenv_ruby_version.stdout | search("ruby-{{ item }}")
  with_items: ruby_versions
