---
- name:     Check if the correct version of Ruby is already installed
  shell: >
    executable=/bin/bash source /usr/local/share/chruby/chruby.sh;
    chruby
  register: chruby_versions

- name:     Debug info
  debug:    msg="{{ chruby_versions.stdout }}"

- name:     Install the versions of Ruby we need
  shell:    ruby-install ruby {{ item }}
  when:     not chruby_versions.stdout | search("ruby-{{ item }}")
  with_items:
    - "{{ ruby_versions }}"
